name: Deploy WeMeet BE

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to server"

            cd /home/ubuntu/we-meet-server

            git pull origin develop

            npm install

            npm run build

            pm2 restart nest-app || pm2 start dist/src/main.js --name nest-app

            pm2 save

            echo "Deploy success"
